spring.application.name=upi-process-service
server.port=8080

# Configuración del cron programacion de ejecuacion
cron.start=0 0 10 ? * 1-7 *
cron.stop=0 0 11 ? * 1-7 *

# Configuración de rutas
route.autostart=true

logging.level.org.apache.camel=DEBUG
logging.level.org.apache.SQL=debug
logging.level.org.apache.camel.dataformat.bindy=TRACE


spring.datasource.url=jdbc:mysql://172.30.107.179:3306/interupi
spring.datasource.username=upidatapp
spring.datasource.password=ms4f3upid4t4.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
spring.jpa.properties.hibernate.format_sql=true


#### CONNECTION POOLING (OPTIONAL) ####
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000


#### PROPERTIES TO BUILD FILE PATH ####
#source.type=file
source.location=src/main/resources/input
target.error.location=src/main/resources/error
target.location=src/main/resources/files/archive
#noop.flag=true
#recursive.flag=true
#file.type=.*.csv

#### PROPERTIES FOR BATCH SIZE AND TIMEOUT ####
#camel.batch.max.records=100
#camel.batch.timeout=1

# propiedades de carpeta para origen, destino y error
#camel.sourcefolder =input/
#camel.destinationfolder =output/
#camel.errorfolder =error/
#spring.task.scheduling.pool.size=2
#camel.springboot.main-run-controller=true
#logging.level.org.apache.camel=debug


# Configuración servidor SFTP
camel.component.sftp.host=sftp-server.com
camel.component.sftp.port=22
camel.component.sftp.username=your-username
camel.component.sftp.password=your-password
camel.component.sftp.directory=/ruta/del/directorio
